### ISSUE TITLE
Logs are not displayed in DataDog's Metrics Explorer

### ISSUE THREAD

**Issue by harumidiv** [DataDog/swift-dogstatsd#9]
I have implemented the following with reference to the readme, but could not send the logs correctly.
Are there any other steps that need to be taken besides the following implementation?

```Swift
public func configure(_ app: Application) async throws {
  try routes(app)

  app.dogstatsd.config = .udp(address: "127.0.0.1", port: 8080)
}

```

``` swift
func routes(_ app: Application) throws {

  app.get { req async in
    req.dogstatsd.increment("custom.swift.metric😺", tags: ["env:prod"])
    return "It works!"
  }
}
```

**Comment by gh123man** [comment]
Hi thanks for reaching out!

- First make sure the [Datadog agent](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent#agent) is running on your host and is configured to accept dogstatsd metrics. Note that the default dogstatsd UDP port is `8125`. 
- Ensure you have a valid API key set in the agent. 

It's also worth pointing out that this library only handles Dogstasd metrics. It does not facilitate sending logs. 
If you would like to collect logs from your application, you can use one of the [Datadog agent log collection methods](https://docs.datadoghq.com/agent/logs/?tab=tailfiles).

**Comment by harumidiv** [comment]
Thank you for your answer!
 I'm sorry that my understanding was wrong. 
This issue will be closed
